[package]
name = "my-rust-blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
sha2 = "0.10.9"
rocket = {version = "0.5.1", features = ["json"] }
serde = "1.0.228"
serde_json = "1.0.149"
sqlx = "0.7.0"
tokio = "1.49.0"
